// Generated by ReScript, PLEASE EDIT WITH CARE


function sendTextToPreview($$event) {
  var tmp = document.getElementById("textView");
  tmp.innerText = $$event.target.value;
  
}

function makeFontSmall(param) {
  var textView = document.getElementById("textView");
  textView.classList.add("text-sm");
  textView.classList.remove("text-2xl", "text-6xl");
  
}

function makeFontRegular(param) {
  var textView = document.getElementById("textView");
  textView.classList.add("text-2l");
  textView.classList.remove("text-sm", "text-6xl");
  
}

function makeFontLarge(param) {
  var textView = document.getElementById("textView");
  textView.classList.add("text-6xl");
  textView.classList.remove("text-2xl", "text-sm");
  
}

function attachEvent(param) {
  var textEditor = document.getElementById("textEditor");
  textEditor.addEventListener("input", sendTextToPreview);
  var selectSmall = document.getElementById("selectSmall");
  selectSmall.addEventListener("change", makeFontSmall);
  var selectRegular = document.getElementById("selectRegular");
  selectRegular.addEventListener("change", makeFontRegular);
  var slectLarge = document.getElementById("selectLarge");
  slectLarge.addEventListener("change", makeFontLarge);
  
}

attachEvent(undefined);

export {
  sendTextToPreview ,
  makeFontSmall ,
  makeFontRegular ,
  makeFontLarge ,
  attachEvent ,
  
}
/*  Not a pure module */
